server:
  #端口号
  port: 8888


################## Mybatis配置
mybatis:
  type-aliases-package: cn.com.cdboost.charge.merchant.model
  mapper-locations: classpath*:/mapper/*Mapper.xml


################## Mapper
mapper:
  mappers: cn.com.cdboost.charge.merchant.common.CommonMapper
  not-empty: false
  identity: MYSQL

################## PageHelper
pagehelper:
  helperDialect: mysql
pagehelper:
  reasonable: true  #为了使用输入页数为负或者超出最大页时候使页数为最小或最大值
pagehelper:
  supportMethodsArguments: true
pagehelper:
  params: count=countSql

################## Druid Datasource配置
spring:
  datasource:
    druid:
      # 驱动配置信息
#      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.10.1.150:3306/cloud_charging_merchant?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia%2FShanghai&useSSL=true&allowMultiQueries=true&nullNamePatternMatchesAll=true
      username: cloudservice
      password: cloud@boost.150

      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j

      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        stat:
          enable: true
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 2000
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true



